"""Regenerate the leaderboards in README.md and records/RECORDS.md from records/records.json.

Multi-track: records carry a "track" field (default t1); each track renders its own
section, with track metadata pulled from its spec file.

Usage:
  python scripts/update_leaderboard.py          # rewrite both files
  python scripts/update_leaderboard.py --check  # CI: fail if files drift from records.json
"""

import argparse
import json
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
START, END = "<!-- LEADERBOARD:START", "<!-- LEADERBOARD:END -->"

SPECS = {}
for f in sorted(REPO_ROOT.glob("spec*.yaml")):
    s = yaml.safe_load(f.read_text())
    SPECS[s.get("track_id", "t1")] = s


def track_title(tid: str) -> str:
    s = SPECS[tid]
    model = s["base_model"].split("/")[-1]
    task = {"gsm8k": "GSM8K", "squad": "SQuAD v1.1"}.get(
        s["dataset"].get("local_prefix", ""), s["dataset"]["repo"])
    n = tid.lstrip("t")
    return (f"Track {n} — {task} · {model} · target ≥ {s['target_accuracy']:.1%} "
            f"· 1× L40S")


def fmt_time(seconds):
    if seconds is None:
        return "_pending_"
    m, s = divmod(int(round(seconds)), 60)
    return f"{m}m {s:02d}s"


def fmt_acc(rec):
    if not rec["accuracies"]:
        return "_pending_"
    return f"{sum(rec['accuracies']) / len(rec['accuracies']):.1%}"


def verified(rec):
    return rec["status"] == "verified" and rec["time_seconds_mean"] is not None


def leaderboard_rows(records):
    rows = []
    prev_time = None
    for rec in records:
        if verified(rec):
            delta = (f"−{(1 - rec['time_seconds_mean'] / prev_time):.0%}"
                     if prev_time else "—")
            prev_time = rec["time_seconds_mean"]
            date = rec["date"]
        else:
            delta, date = "—", "_pending_"
        desc = rec["description"]
        if rec.get("verification_report"):
            desc += f" ([report]({rec['verification_report']}))"
        rows.append(f"| {rec['id']} | {date} | [@{rec['github']}](https://github.com/{rec['github']}) "
                    f"| {fmt_time(rec['time_seconds_mean'])} | {fmt_acc(rec)} | {delta} | {desc} |")
    return rows


def track_section(tid, records, level=3):
    recs = [r for r in records if r.get("track", "t1") == tid]
    hashes = "#" * level
    lines = [f"{hashes} {track_title(tid)}", ""]
    latest = next((r for r in reversed(recs) if verified(r)), None)
    if latest:
        lines.append(f"**Current record: {fmt_time(latest['time_seconds_mean'])}** by "
                     f"[@{latest['github']}](https://github.com/{latest['github']}) — "
                     f"{latest['description']}")
    else:
        lines.append("**Current record:** _none yet — this track is open for its first record._")
    lines += ["",
              "| # | Date | Author | Train time | GSM8K/EM | Δ | Technique |",
              "|---|------|--------|-----------|----------|---|-----------|"]
    lines += leaderboard_rows(recs) or ["| — | | | | | | _no entries yet_ |"]
    return lines


def build_block(data):
    records = data["records"]
    lines = [f"{START} — auto-generated by scripts/update_leaderboard.py, do not edit by hand -->"]
    for tid in sorted(SPECS):
        lines += track_section(tid, records)
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def build_records_md(data):
    lines = ["# Records",
             "",
             "<!-- AUTO-GENERATED by scripts/update_leaderboard.py from records/records.json — do not edit by hand -->",
             "",
             "Wall-clock record progression per track. Every verified record links its",
             "submission folder and its public verification report.",
             ""]
    for tid in sorted(SPECS):
        lines += track_section(tid, data["records"], level=2)
        lines.append("")
    lines += ["## Notable attempts", ""]
    if data["notable_attempts"]:
        for na in data["notable_attempts"]:
            lines.append(f"- **[@{na['github']}](https://github.com/{na['github']})** — "
                         f"{na['description']} ([submission]({na['submission']}))")
    else:
        lines.append("_None yet. A notable attempt is a merged submission that didn't take the "
                     "record but taught us something — see CONTRIBUTING.md._")
    lines += ["", "## How records are verified", "",
              "Every entry above was re-run 3× with fresh seeds on spec hardware by a verifier",
              "before merge — see [JUDGING.md](../JUDGING.md). Full reports live in",
              "[verifications/](./verifications/).", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    data = json.loads((REPO_ROOT / "records" / "records.json").read_text())

    readme_path = REPO_ROOT / "README.md"
    readme = readme_path.read_text()
    i, j = readme.index(START), readme.index(END) + len(END)
    new_readme = readme[:i] + build_block(data) + readme[j:]

    records_path = REPO_ROOT / "records" / "RECORDS.md"
    new_records = build_records_md(data)
    old_records = records_path.read_text() if records_path.exists() else ""

    if args.check:
        drift = []
        if new_readme != readme:
            drift.append("README.md leaderboard")
        if new_records != old_records:
            drift.append("records/RECORDS.md")
        if drift:
            print(f"DRIFT: {', '.join(drift)} out of date with records/records.json.\n"
                  f"Run: python scripts/update_leaderboard.py")
            sys.exit(1)
        print("leaderboard in sync ✓")
        return

    readme_path.write_text(new_readme)
    records_path.write_text(new_records)
    print("README.md + records/RECORDS.md regenerated")


if __name__ == "__main__":
    main()
